### ISSUE TITLE
Some confusions about  the paper.

### ISSUE THREAD

**Issue by FlyingGaifield** [jmfacil/camconvs#1]
Hi, Sir:
After reading your paper, I have a confusion that whether the Cam-Conv module or the data augmentation helps improve the accuracy? Thx.

**Comment by jmfacil** [comment]
Hi!! I am sorry I get notified and I have been out of office. As we say in the paper both. 1) Cam-Convs allow to train with multiple cameras and learn to leverage from known calibration and 2) training with multiple cameras (by data augmentation) let the network learn to use calibration.

 If you train only with one camera calibration is a constant during training and the network is going to ignore this.

**Comment by jmfacil** [comment]
If you have more questions let me know :).
